export const CategoryItems = ["Toutes nos Catégories","Ventes Flash",
                            "Alexa Skills",
                            "Amazon Warehouse",
                            "Animalerie",
                            "Appareils Amazon",
                            "Appli & Jeux",
                            "Auto et Moto",
                            "Bagages",
                            "Beautés et parfum",
                            "Beauté Premium",
                            "Bijoux",
                            "Boutique chèques-cadeaux",
                            "Boutique Kindle",
                            "Bricolage",
                            "Bébés et Puéricultures",
                            "Chaussures et Sacs",
                            "Cuisine et Maison",
                            "DVD et Blu-ray",
                            "Epicerie",
                            "Fournitures de bureau",
                            "Gros électroménager",
                            "Handmade",
                            "High-Tech",
                            "Hygiène et Santé",
                            "Informatique",
                            "Instrument de musique & Sono",
                            "Jardin",
                            "Jeux et Jouets",
                            "Jeux vidéo",
                            "Livres anglais et étrangers",
                            "Livres",
                            "Logiciels",
                            "Sports et Loisirs"
                        ]
