export const LocationList1 = ["Allemagne","Belgique","Chine","France","États-Unis","Luxembourg","Monaco","Suisse"]
export const LocationList2 = [
	"Afrique du Sud",
	"Albanie",
	"Algérie",
	"Allemagne",
	"Andorre",
	"Angola",
	"Anguilla",
	"Antigua-et-Barbuda",
	"Antilles néerlandaises",
	"Arabie Saoudite",
	"Argentine",
	"Arménie",
	"Aruba",
	"Australie",
	"Autriche",
	"Azerbaïdjan",
	"Bahamas",
	"Bahreïn",
	"Bangladesh",
	"Barbade",
	"Belgique",
	"Bermudes",
	"Bélize",
	"Bénin",
	"Bhoutan",
	"Biélorussie",
	"Bolivie",
	"Bonaire, Saint Eustatius et Saba",
	"Bosnie-Herzégovine",
	"Botswana",
	"Brésil",
	"Brunéi Darussalam",
	"Bulgarie",
	"Burkina Faso",
	"Burundi",
	"Cambodge",
	"Cameroun",
	"Canada",
	"Cap Vert",
	"Chili",
	"Chine",
	"Chypre",
	"Colombie",
	"Comores",
	"Congo",
	"Congo, République démocratique du",
	"Corée, République de",
	"Costa Rica",
	"Côte d'ivoire",
	"Croatie",
	"Curaçao",
	"Danemark",
	"Djibouti",
	"Dominique",
	"El Salvador",
	"Espagne",
	"Estonie",
	"Ethiopie",
	"Égypte",
	"Émirats arabes unis",
	"Équateur",
	"Érythrée",
	"États-Unis",
	"Fédération de Russie",
	"Fidji",
	"Finlande",
	"France",
	"Gabon",
	"Gambie",
	"Géorgie ",
	"Géorgie du Sud et les Îles Sandwich du Sud",
	"Ghana",
	"Gibraltar",
	"Grenade",
	"Grèce",
	"Groenland",
	"Guadeloupe",
	"Guam",
	"Guatemala",
	"Guinée",
	"Guinée équatoriale",
	"Guinée-Bissau",
	"Guyane",
	"Guyane française",
	"Haïti",
	"Honduras",
	"Hong Kong",
	"Hongrie",
	"Inde",
	"Indonésie",
	"Irlande",
	"Islande",
	"Israël",
	"Italie",
	"Île Bouvet",
	"Île Christmas",
	"Île Heard et îles McDonald",
	"Îles Caïmans",
	"Îles Cocos (Keeling)",
	"Îles Cook",
	"Îles Falkland (Malouines)",
	"Îles Féroé",
	"Îles Mariannes du Nord",
	"Îles Marshall",
	"Îles Salomon",
	"Îles Turques-et-Caïques",
	"Îles Vierges américaines",
	"Îles Vierges britanniques",
	"Îles mineures éloignées des États-Unis",
	"Jamaïque",
	"Japon",
	"Jordanie",
	"Kazakhstan",
	"Kenya",
	"Kirghizistan",
	"Kiribati",
	"Kosovo",
	"Koweït",
	"Lesotho",
	"Lettonie",
	"Liban",
	"Liberia",
	"Libye ",
	"Liechtenstein",
	"Lituanie",
	"Luxembourg",
	"Macao",
	"Macédoine, Ex-République yougoslave de",
	"Madagascar",
	"Malaisie",
	"Malawi",
	"Maldives",
	"Mali",
	"Malte",
	"Maroc",
	"Martinique",
	"Maurice",
	"Mauritanie",
	"Mayotte",
	"Mexique",
	"Micronésie, États fédérés de",
	"Monaco",
	"Mongolie",
	"Montenegro",
	"Montserrat",
	"Mozambique",
	"Myanmar",
	"Namibie",
	"Nauru",
	"Népal",
	"Nicaragua",
	"Niger",
	"Nigeria",
	"Niué",
	"Norvège",
	"Nouvelle-Calédonie",
	"Nouvelle-Zélande",
	"Oman",
	"Ouganda",
	"Ouzbékistan",
	"Pakistan",
	"Palaos",
	"Panama",
	"Papouasie-Nouvelle-Guinée",
	"Paraguay",
	"Pays-Bas",
	"Pérou",
	"Philippines",
	"Pitcairn",
	"Pologne",
	"Polynésie française",
	"Porto Rico",
	"Portugal",
	"Qatar",
	"République Tchèque",
	"République centrafricaine",
	"République de Moldavie",
	"République démocratique populaire lao",
	"République dominicaine",
	"Réunion",
	"Roumanie",
	"Royaume-Uni",
	"Rwanda",
	"Sahara occidental",
	"Saint-Barthélemy ",
	"Saint-Kitts-et-Nevis",
	"Saint-Marin",
	"Saint-Martin (France)",
	"Saint-Martin (Pays Bas)",
	"Saint-Pierre-et-Miquelon",
	"Saint-Siège",
	"Saint-Vincent-et-les Grenadines",
	"Sainte-Hélène, Ascension et Tristan da Cunha",
	"Sainte-Lucie",
	"Samoa",
	"Samoa américaines",
	"Sao-Tomé-et-Principe",
	"Serbie",
	"Seychelles",
	"Sénégal",
	"Sierra Leone",
	"Singapour",
	"Slovaquie",
	"Slovénie",
	"Somalie",
	"Sri Lanka",
	"Suède",
	"Suisse",
	"Surinam",
	"Svalbard et Jan Mayen",
	"Swaziland",
	"Tadjikistan",
	"Taïwan",
	"Tanzanie, République unie de",
	"Tchad",
	"Terres australes et antarctiques françaises",
	"Territoire britannique de l'océan Indien",
	"Territoires palestiniens",
	"Thaïlande",
	"Timor-leste",
	"Togo",
	"Tokelau",
	"Tonga",
	"Trinité-et-Tobago",
	"Tunisie",
	"Turkménistan",
	"Turquie",
	"Tuvalu",
	"Ukraine",
	"Uruguay",
	"Vanuatu",
	"Venezuela",
	"Vietnam",
	"Wallis-et-Futuna",
	"Yémen",
	"Zambie",
	"Zimbabwe",
];
